website:
  sidebar:
    contents:
    - section: Home
      contents:
      - text: Introduction
        href: index.qmd
    - section: '2025-12-09'
      contents:
      - text: Blob inclusion
        href: notebooks/01-blob-inclusion.qmd
      - text: Blob flow
        href: notebooks/02-blob-flow.qmd
      - text: Column propagation
        href: notebooks/03-column-propagation.qmd
    - section: Historical
      contents:
      - text: '2025-12-08'
        href: 20251208/index.html
